data_cfg = {
    "train": {
        "desc": "training data for the open loop prediction accuracy",
        "id": "certain_open_loop_experiment",
        "vary_input": True,
        "input_bounds": [(535, 665), (535, 665), (535, 665), (535, 665)],  # use wider ranges so the networks will never extrapolate during inference
        "vary_tvp": True,
        "tvp_bounds": (0.18, 0.42),
        "use_true_model_params": False,
        "covaraince_gain": 3,
        "lam_bed_std": 0.08,
        "t_steps": 1024,
        "tvp_signal_tau": 35,
        "input_signal_tau": 12,
        "n_trajectories": -1,
        "n_workers": 10,
        "data_purpose": "train",
    },
    "test": {
        "desc": "test data for the open loop prediction accuracy",
        "id": "certain_open_loop_experiment",
        "vary_input": False,
        "input_bounds": [(550, 650), (550, 650), (550, 650), (550, 650)],
        "vary_tvp": False,
        "tvp_bounds": (0.2, 0.4),
        "use_true_model_params": False,  # False samples new parameters for every simulation
        "covaraince_gain": 3,
        "lam_bed_std": 0.08,
        "t_steps": 512,
        "tvp_signal_tau": 35,
        "input_signal_tau": 12,
        "n_trajectories": -1,
        "n_workers": 10,
        "data_purpose": "test",
    },
}

training_cfgs = [
    {
        "hidden_units": [16],
        "input_length": 16,
        "lr": 5e-5,
        "sigma_weight": 0.002,
        "early_stopping": True,
        "max_epochs": 768,
        "batch_size": 1024,
        "training_ratio": 0.8,
        "n_trajectories": -1,
        "save_history": True,
        "pca_encoder": {"name": "pca_encoder"},
        "save_dir": "vanilla",
        "training_jobs": {
            "nominal_states": {
                "name": "nominal_states",
                "state_key": "x",
                "last_layer_activation": "vanilla",
                "loss_function": "mse",
            },
            "nominal_temperature": {
                "name": "nominal_temperature",
                "state_key": "T",
                "last_layer_activation": "vanilla",
                "loss_function": "mse",
            },
            "upper_temperature": {
                "name": "upper_temperature",
                "state_key": "T",
                "last_layer_activation": "vanilla",
                "loss_function": "quantile",
                "quantile": 0.9,
            },
            "lower_temperature": {
                "name": "lower_temperature",
                "state_key": "T",
                "last_layer_activation": "vanilla",
                "loss_function": "quantile",
                "quantile": 0.1,
            },
            "upper_states": {
                "name": "upper_states",
                "state_key": "x",
                "last_layer_activation": "vanilla",
                "loss_function": "weighted",
                "quantile": 0.9,
            },
            "lower_states": {
                "name": "lower_states",
                "state_key": "x",
                "last_layer_activation": "vanilla",
                "loss_function": "weighted",
                "quantile": 0.1,
            },
        },
    },
    {
        "hidden_units": [16],
        "input_length": 16,
        "lr": 5e-5,
        "sigma_weight": 0.002,
        "early_stopping": True,
        "max_epochs": 768,
        "batch_size": 1024,
        "training_ratio": 0.8,
        "n_trajectories": -1,
        "save_history": True,
        "pca_encoder": {"name": "pca_encoder"},
        "save_dir": "pc",
        "early_stopping": False,
        "training_jobs": {
            "nominal_states": {
                "name": "nominal_states",
                "state_key": "x",
                "last_layer_activation": "physics_constrained",
                "loss_function": "mse",
            },
            "nominal_temperature": {
                "name": "nominal_temperature",
                "state_key": "T",
                "last_layer_activation": "physics_constrained",
                "loss_function": "mse",
            },
            "upper_temperature": {
                "name": "upper_temperature",
                "state_key": "T",
                "last_layer_activation": "physics_constrained",
                "loss_function": "quantile",
                "quantile": 0.9,
            },
            "lower_temperature": {
                "name": "lower_temperature",
                "state_key": "T",
                "last_layer_activation": "physics_constrained",
                "loss_function": "quantile",
                "quantile": 0.1,
            },
            "upper_states": {
                "name": "upper_states",
                "state_key": "x",
                "last_layer_activation": "physics_constrained",
                "loss_function": "weighted",
                "quantile": 0.9,
            },
            "lower_states": {
                "name": "lower_states",
                "state_key": "x",
                "last_layer_activation": "physics_constrained",
                "loss_function": "weighted",
                "quantile": 0.1,
            },
        },
    },
]

test_cfg_list = [
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop upper bound",
        "surrogate_type": "vanilla",
        "state_dict_folder": "vanilla",
        "scenario": "nominal",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "vanilla/nominal",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop upper bound",
        "surrogate_type": "vanilla",
        "state_dict_folder": "vanilla",
        "scenario": "upper",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "vanilla/upper",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop lower bound",
        "surrogate_type": "vanilla",
        "state_dict_folder": "vanilla",
        "scenario": "lower",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "vanilla/lower",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop upper bound",
        "surrogate_type": "naive_pc",
        "state_dict_folder": "vanilla",
        "scenario": "nominal",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "naive_pc/nominal",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop upper bound",
        "surrogate_type": "naive_pc",
        "state_dict_folder": "vanilla",
        "scenario": "upper",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "naive_pc/upper",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop lower bound",
        "surrogate_type": "naive_pc",
        "state_dict_folder": "vanilla",
        "scenario": "lower",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "naive_pc/lower",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "pc_narx_open_loop",
        "surrogate_type": "pc",
        "state_dict_folder": "pc",
        "scenario": "nominal",
        "t_steps": 480,
        "warm_up_steps": 10,
        "n_test_trajectories": -1,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "pc/nominal",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "chi_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "pc_narx_open_loop",
        "surrogate_type": "pc",
        "state_dict_folder": "pc",
        "scenario": "upper",
        "t_steps": 480,
        "warm_up_steps": 10,
        "n_test_trajectories": -1,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "pc/upper",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "chi_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "pc_narx_open_loop",
        "surrogate_type": "pc",
        "state_dict_folder": "pc",
        "scenario": "lower",
        "t_steps": 480,
        "warm_up_steps": 10,
        "n_test_trajectories": -1,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "pc/lower",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "chi_EO"],
        },
    },
]
