data_cfg = {
    "train": {
        "desc": "training data for the open loop prediction accuracy",
        "vary_input": True,
        "input_bounds": [(535, 665), (535, 665), (535, 665), (535, 665)],  # use wider ranges so the networks will never extrapolate during inference
        "vary_tvp": True,
        "tvp_bounds": (0.18, 0.42),
        "use_true_model_params": False,
        "covaraince_gain": 3,
        "lam_bed_std": 0.08,
        "t_steps": 1024,
        "tvp_signal_tau": 35,
        "input_signal_tau": 12,
        "n_trajectories": 1000,
        "n_workers": 10,
        "data_purpose": "train",
    },
    "calibration": {
        "desc": "calibration data to perform conformalized quantile regression",
        "vary_input": True,
        "input_bounds": [(535, 665), (535, 665), (535, 665), (535, 665)],  # use wider ranges so the networks will never extrapolate during inference
        "vary_tvp": True,
        "tvp_bounds": (0.18, 0.42),
        "use_true_model_params": False,
        "covaraince_gain": 3,
        "lam_bed_std": 0.08,
        "t_steps": 1024,
        "tvp_signal_tau": 35,
        "input_signal_tau": 12,
        "n_trajectories": 1000,
        "n_workers": 9,
        "data_purpose": "calibration",
    },
    "test": {
        "desc": "test data for the open loop prediction accuracy",
        "vary_input": False,
        "input_bounds": [(550, 650), (550, 650), (550, 650), (550, 650)],
        "vary_tvp": False,
        "tvp_bounds": (0.2, 0.4),
        "use_true_model_params": False,  # False samples new parameters for every simulation
        "covariance_gain": 3,
        "lam_bed_std": 0.08,
        "t_steps": 512,
        "tvp_signal_tau": 35,
        "input_signal_tau": 12,
        "n_trajectories": 100,
        "n_workers": 10,
        "data_purpose": "test",
    },
}

training_cfgs = [
    {
        "hidden_units": [32],
        "input_length": 16,
        "lr": 5e-5,
        "sigma_weight": 0.001,
        "save_distances": False,
        "early_stopping": True,
        "max_epochs": 768,
        "min_epochs": 128,
        "batch_size": 1024,
        "training_ratio": 0.8,
        "n_trajectories": -1,
        "n_calibration_trajectories": -1,
        "significance_level": 0.2,
        "calibrate_quantiles": True,
        "save_history": False,
        "pca_encoder": {"name": "pca_encoder"},
        "save_dir": "vanilla",
        "training_jobs": {
            "nominal_states": {"name": "nominal_states", "state_key": "x", "last_layer_activation": "vanilla", "loss_function": "mse"},
            "nominal_temperature": {"name": "nominal_temperature", "state_key": "T", "last_layer_activation": "vanilla", "loss_function": "mse"},
            "upper_temperature": {
                "name": "upper_temperature",
                "state_key": "T",
                "last_layer_activation": "vanilla",
                "loss_function": "quantile",
                "quantile": 0.90,
                # "hidden_units": [64, 72],
                # "lr": 1e-5,
            },
            "lower_temperature": {
                "name": "lower_temperature",
                "state_key": "T",
                "last_layer_activation": "vanilla",
                "loss_function": "quantile",
                "quantile": 0.1,
                # "hidden_units": [64, 72],
                # "lr": 1e-5,
            },
            "upper_states": {"name": "upper_states", "state_key": "x", "last_layer_activation": "vanilla", "loss_function": "weighted", "quantile": 0.90},
            "lower_states": {"name": "lower_states", "state_key": "x", "last_layer_activation": "vanilla", "loss_function": "weighted", "quantile": 0.1},
        },
    },
    {
        "hidden_units": [32],
        "input_length": 16,
        "lr": 5e-5,
        "sigma_weight": 0.001,
        "early_stopping": True,
        "max_epochs": 768,
        "min_epochs": 128,
        "batch_size": 1024,
        "training_ratio": 0.8,
        "n_trajectories": -1,
        "n_calibration_trajectories": -1,
        "significance_level": 0.2,
        "calibrate_quantiles": True,
        "save_history": True,
        "pca_encoder": {"name": "pca_encoder"},
        "save_dir": "pc",
        "training_jobs": {
            "nominal_states": {"name": "nominal_states", "state_key": "x", "last_layer_activation": "physics_constrained", "loss_function": "mse"},
            "nominal_temperature": {"name": "nominal_temperature", "state_key": "T", "last_layer_activation": "vanilla", "loss_function": "mse"},
            "upper_temperature": {
                "name": "upper_temperature",
                "state_key": "T",
                "last_layer_activation": "vanilla",
                "loss_function": "quantile",
                "quantile": 0.9,
                # "hidden_units": [64, 72],
                # "lr": 1e-5,
            },
            "lower_temperature": {
                "name": "lower_temperature",
                "state_key": "T",
                "last_layer_activation": "vanilla",
                "loss_function": "quantile",
                "quantile": 0.1,
                # "hidden_units": [64, 72],
                # "lr": 1e-5,
            },
            "upper_states": {"name": "upper_states", "state_key": "x", "last_layer_activation": "physics_constrained", "loss_function": "weighted", "quantile": 0.9},
            "lower_states": {"name": "lower_states", "state_key": "x", "last_layer_activation": "physics_constrained", "loss_function": "weighted", "quantile": 0.1},
        },
    },
]

test_cfg_list = [
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop upper bound",
        "surrogate_type": "vanilla",
        "state_dict_folder": "vanilla",
        "scenario": "nominal",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "vanilla/nominal",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop upper bound",
        "surrogate_type": "vanilla",
        "state_dict_folder": "vanilla",
        "scenario": "upper",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "vanilla/upper",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop lower bound",
        "surrogate_type": "vanilla",
        "state_dict_folder": "vanilla",
        "scenario": "lower",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "vanilla/lower",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop upper bound",
        "surrogate_type": "naive_pc",
        "state_dict_folder": "vanilla",
        "scenario": "nominal",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "naive_pc/nominal",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop upper bound",
        "surrogate_type": "naive_pc",
        "state_dict_folder": "vanilla",
        "scenario": "upper",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "naive_pc/upper",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "uncertain narx_open_loop lower bound",
        "surrogate_type": "naive_pc",
        "state_dict_folder": "vanilla",
        "scenario": "lower",
        "t_steps": 480,
        "warm_up_steps": 10,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "naive_pc/lower",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "c_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "pc_narx_open_loop",
        "surrogate_type": "pc",
        "state_dict_folder": "pc",
        "scenario": "nominal",
        "t_steps": 480,
        "warm_up_steps": 10,
        "n_test_trajectories": -1,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "pc/nominal",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "chi_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "pc_narx_open_loop",
        "surrogate_type": "pc",
        "state_dict_folder": "pc",
        "scenario": "upper",
        "t_steps": 480,
        "warm_up_steps": 10,
        "n_test_trajectories": -1,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "pc/upper",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "chi_EO"],
        },
    },
    {
        "desc": "results for the surrogate open loop prediction",
        "id": "pc_narx_open_loop",
        "surrogate_type": "pc",
        "state_dict_folder": "pc",
        "scenario": "lower",
        "t_steps": 480,
        "warm_up_steps": 10,
        "n_test_trajectories": -1,
        "kinetic_parameter_type": "default",
        "n_workers": 1,
        "sub_directory": "pc/lower",
        "plausibility_plot": {
            "n_trajectories": 3,
            "states": ["T", "chi_EO"],
        },
    },
]

uq_test_cfg = {
    "n_experiments": 100,
    "N_fp_trajects": 200,
    "n_fp_workers": 9,
    "n_narx_workers": 1,
    "t_steps": 512,
    "warm_up_steps": 10,
    "surrogate_types": ["vanilla", "naive_pc", "pc"],
    "state_dict_folders": ["vanilla", "vanilla", "pc"],
    "input_signal_tau": 15,
}

mpc_perf_cfg = {
    "n_experiments": 7,
    "n_workers": 7,
    "covariance_gain": 3,
    "lam_bed_std": 0.08,
    "tvp_tau": 20,
    "surrogate_types": ["pc"],
    # "surrogate_types": ["pc", "naive"],
    "state_dict_folder": {"vanilla": "vanilla", "naive": "vanilla", "pc": "pc"},
    "t_steps": 384,
    "mpc_cfg": {
        "input_bounds": {"lower": 580, "upper": 625},
        "n_horizon": 25,
        "n_robust": 1,
        "uncertainty_values": {"alpha": [[1, 0], [0, 1]]},
        "scenarios": ["nominal", "upper"],
        "t_step": 1,
        "lam_Tmax": 1e3,
        "ub_T": 630 / 625,
        "lam_dudt": {"T_c0": 500, "T_c1": 10, "T_c2": 10, "T_c3": 10},
        "lam_X": 2e1,
        "lam_T_Tcool": 1e3,
        "lb_X": 0.5,
        "input_scale": 625,
        "tvp_scale": 0.4,
        "store_full_solution": False,
        "surpress_ipopt_output": False,
        "BLAS_NUM_THREADS": "1",
        "solver_opts": {
            "ipopt": {
                "max_iter": 1000,
                "tol": 1e-4,
                "acceptable_tol": 5e-4,
                "print_level": 5,
                "warm_start_init_point": "yes",
                # "linear_solver": "mumps",
                "linear_solver": "ma57",
                "hessian_approximation": "limited-memory",
            }
        },
    },
}
